#include "device_registers.h"
#include "port.h"

void common_init()
{
	COMMON_PORTN->PCR[COMMON_EMERGENCY] |= PORT_PCR_MUX(1) | PORT_PCR_IRQC(10);
	COMMON_PTN->PDDR &= ~(1 << COMMON_EMERGENCY);
	
	COMMON_PORTN->PCR[testSW] |= PORT_PCR_MUX(1) | PORT_PCR_IRQC(10);
	COMMON_PTN->PDDR &= ~(1 << testSW);

	COMMON_PORTN->PCR[COMMON_EDIT] |= PORT_PCR_MUX(1) | PORT_PCR_IRQC(10);
	COMMON_PTN->PDDR &= ~(1 << COMMON_EDIT);
}